### ISSUE TITLE
Retry on idempotent methods

### ISSUE THREAD

**Issue by shinsuke-nara** [KiiPlatform/thing-if-AndroidSDK#101]
Retry on OPTIONS/HEAD/GET/PUT/DELETE but not on POST/PATCH when network error happen.

Related issue: No. 798
Release version: 0.13.0

**Comment by naoki-akimoto** [comment]
@shinsuke-nara 
[IoTRestClient#75](https://github.com/KiiPlatform/thing-if-AndroidSDK/blob/develop/thingif/src/main/java/com/kii/thingif/internal/http/IoTRestClient.java#75) 近辺でsetRetryOnConnectionFailure(false)を設定しています。
これが実際には動いていないというのがこのIssueの要件でしょうか？
RetryOnConnectionFailureは初期値がtrueなので設定していない場合はリトライされるはずです。

**Comment by shinsuke-nara** [comment]
@satoshikumano 現状の実装でリトライの設定がされているように見受けられます。

確認箇所は以下になります。
https://github.com/KiiPlatform/thing-if-AndroidSDK/blob/develop/thingif/src/main/java/com/kii/thingif/internal/http/IoTRestClient.java#L66

私としては、HTTP通信で、通信エラーが発生した際に以下のHTTPメソッドの場合はリトライを行うというissueだと認識しています。

  * OPTIONS
  * HEAD
  * GET
  * PUT
  * DELETE

このissueは「HEAD/GET/DELETEについては、対応済み。OPTIONSについてはHTTPClient自体が対応していないので、これに対応する」という内容でよろしいでしょうか。

また、issueにはPUTもretry対応すると記載されていますが、PUTはレコードのaddなどに使われるように思われるので、retryをしてしまうと、データの重複等が発生しうると思います。PUTについてもretryするよう変更してよろしいでしょうか。

確認よろしくお願いします。

**Comment by satoshikumano** [comment]
OPTIONSは対応不要です。

> PUTはレコードのaddなどに使われるように思われるので、retryをしてしまうと、データの重複等が発生しうると思います。

PUTではリソースのIDを指定するので重複は起こりません。
競合した場合の動作はif-match/if-none-matchの指定するのでリトライしても問題ないです。

**Comment by shinsuke-nara** [comment]
@satoshikumano ありがとうございます。そのように対応します。
@naoki-akimoto 上記の通りお願いします。

**Comment by naoki-akimoto** [comment]
@satoshikumano PUTに関してリトライしても問題ないのはわかりますが、PUTのように大きいデータを扱う可能性がある場合に再送を行うのはユーザの通信料に影響があるのですが、それでもリトライさせるべきと指示していると受け取っていいのでしょうか？

**Comment by satoshikumano** [comment]
@naoki-akimoto 
確かにそうですね。
thing-if SDKで扱うデータは大きくないので問題ないと思います。
将来的に大きなデータを扱うようなAPIが追加される場合には、そのAPIについて考慮の必要あるかもしれませんが今回はリトライする形でお願いします。

**Comment by naoki-akimoto** [comment]
確認のうえ閉じてください。
