### ISSUE TITLE
change Trigger#getTargetID() return value

### ISSUE THREAD

**Issue by naoki-akimoto** [KiiPlatform/thing-if-AndroidSDK#110]
Trigger#getTargetID()は現在Triggerの持つCommandのターゲットIDを返すように実装されています。
しかしこれではクロストリガーが行われた場合にTriggerのターゲットIDを正しく表せません。
Triggerを作成する際に利用するThingIFAPIのターゲットのIDを持つように修正してください。

注意: 現在のTriggerはRestAPIの応答JSONをそのままパースしてインスタンスを作成するようになってます。
Trigger自身のターゲットIDはRestAPIの応答には含まれないので別途パース後に設定する必要があります。

関連Issue: #108

**Comment by shinsuke-nara** [comment]
マージ済みなのでcloseします。
