### ISSUE TITLE
Determine new data class for trigger APIs.

### ISSUE THREAD

**Issue by shinsuke-nara** [KiiPlatform/thing-if-AndroidSDK#120]
新しい`postNewTrigger()`と`patchTrigger()`の設計に伴い、Commandを表現するクラスの設計が必要になりました。このissueでは、これら提案する3の方法のうち、どれが良いか。または別の方法をとるべきかを議論します。

### データクラスの数
まず、いくつのデータクラスを作成するべきかについてです。
Commandを扱うメソッドは以下の3つになります。

  * `postNewCommand()`
  * `postNewTrigger()`
  * `patchTrigger()`

これら3つで、`postNewTrigger()`と`patchTrigger()`は同じデータを扱うことになります。
`postNewCommand()`のみ、commandのtargetを設定しても意味がないので、異なるデータを扱うことになります。

なので、作成するデータクラスは最大で2つで充分という認識です。

`patchTrigger()` は作成したtriggerの更新処理なので、`postNewTrigger()`より少ないデータで可能というように見えてしまいます。しかし、`patchTrigger()`では、Command全部を更新します。部分更新ができないため、`postNewTrigger()`と`patchTrigger()`では同じデータが必要になります。

### command/targetの扱い

commandのtargetはコマンドが発行される先のthing idを指定します。このサーバサイドでの扱いが`postNewCommand()`と`postNewTrigger()`、`patchTrigger()`では異なります。

#### `postNewCommand()` のtargetのサーバサイドでの扱い

`postNewCommand()` では、commandのtargetは常に無視されます。コマンドのターゲットは常にREST APIのパス部分に指定されたthing idが利用されます。

#### `postNewTrigger()`と`patchTrigger()`のtargetのサーバサイドでの扱い

`postNewTrigger()`、`patchTrigger()`ともに、commandのtargetが指定された場合は、その値がコマンドの発行先のターゲットとなります。
ただし、commandのtargetは省略可能です。省略された場合はREST APIのパス部分に指定されたthing idが利用されます。

このため、`patchTrigger()`でcommandのtargetを省略した場合の挙動が、直感に反する形になっていると思われます。cross thing triggerとして作成されたtriggerに対して、commandのtargetを省略した`patchTrigger()`を発行してしまうと、ターゲットが変更されてしまうためです。直感的には指定されなかった場合は、以前の値を採用されていると考えるように思います。

### 設計の選択の基準

現状は上述したとおりです。私の考えるポイントは以下のとおりです。

1. `postNewCommand()`と`postNewTrigger()`、`patchTrigger()`は同じCommandを利用するが、`postNewCommand()`はcommandのtargetを無視し、`postNewTrigger()`と`patchTrigger()`は利用する。この場合、1つのCommandデータクラスを全てで扱う場合、ユーザにその点を認識して貰わなければならない。
2. `postNewCommand()`と`postNewTrigger()`、`patchTrigger()`で別のデータクラスを使ったとしても、targetをサーバ実装通り、optionalな値とすると、直感に反した挙動が起る。結果、ユーザが想定しない形でcommandのtargetが変更されかねない。

個人的にはどの点まで許容するのかという話しになると思います。

### PRの説明

#118 は1, 2ともに許容する方式です。既存の`CommandForm`クラスを拡張し、targetを設定出来るようにしました。加えて、`patchTrigger()`のために、すべての要素の変更に対応するため、すべてのフィールドに対してsetterを追加しました。

#119 は2のみ許容する方式です。`TriggeredCommandForm`クラスを新しく導入しました。targetはoptionalとし、デフォルト値を許容しています。

#117 は、1, 2ともに許容しない方式です。こちらも`TriggeredCommandForm`クラスを導入していますが、targetを必須の項目とすることで対応しています。#117は他の部分のAPI設計なども含んでいます。ご了承ください。

`CommandForm`、`TriggeredCommandForm`のどのバージョンにも`Command`からインスタンスを作成するコンストラクタを追加してあります。`patchTrigger()`でtargetが書き換わってしまう課題は、このコンストラクタを使えばどのバージョンでもある程度は緩和できるかと思います。ただ、#117は指定を強制するので、それに比べると弱いです。

**Comment by satoshikumano** [comment]
@shinsuke-nara 
#119 の方針でお願いします。

Builderクラスを用意したほうがいいですね。
既存のコマンドから作成する場合
Builder#buildFromCommand のようなメソッドを使う。

**Comment by shinsuke-nara** [comment]
#119 の方針で進めることに決定しましたため、このissueをcloseします。
