### ISSUE TITLE
Review unnecessary public setter methods

### ISSUE THREAD

**Issue by naoki-akimoto** [KiiPlatform/thing-if-AndroidSDK#122]
以下のセッターメソッドは現在要らないと目されています。
これらを実際に削除した場合、実現できなくなるユースケースがあるか、精査してください。

    cd thing-if/thing-if-AndroidSDK/thingif/src/main/java
    grep -srI 'public\s*void\s*set' .
    ./com/kii/thingif/command/Command.java:    public void setTitle(String title) {
    ./com/kii/thingif/command/Command.java:    public void setDescription(String description) {
    ./com/kii/thingif/command/Command.java:    public void setMetadata(JSONObject metadata) {
    ./com/kii/thingif/trigger/StatePredicate.java:    public void setCondition(@NonNull Condition condition) {
    ./com/kii/thingif/trigger/StatePredicate.java:    public void setTriggersWhen(@NonNull TriggersWhen triggersWhen) {
    ./com/kii/thingif/trigger/Trigger.java:    public void setDisabled(boolean disabled) {
    ./com/kii/thingif/trigger/Trigger.java:    public void setTitle(String title) {
    ./com/kii/thingif/trigger/Trigger.java:    public void setDescription(String description) {
    ./com/kii/thingif/trigger/Trigger.java:    public void setMetadata(JSONObject metadata) {
    ./com/kii/thingif/trigger/TriggeredServerCodeResult.java:    public void setEndpoint(String endpoint) {

No.958

**Comment by naoki-akimoto** [comment]
@satoshikumano @shinsuke-nara 

Command.javaの3つのセッターメソッドに関しては `ThingIFAPI.getNewCommand(CommandForm)` 内で送信ボディ用のCommandを作成する際に使用しています。
セッターメソッドをpackage internalにして値供給元のCommandFormからビルドする形にすれば問題なく修正できると思われます。

奈良さんからは送信ボディ用にCommandを使うのはおかしいのではないか、との意見も出ましたが、CommandがRestAPIのコマンドをマップするものであると捉えると問題ないと判断出来ました。

CommandFormからビルドする形で別Issueを立てる方向でよろしいでしょうか？

**Comment by shinsuke-nara** [comment]
@naoki-akimoto @satoshikumano 

> セッターメソッドをpackage internalにして値供給元のCommandFormからビルドする形にすれば問題なく修正できると思われます。

このissueのポイントは「ユーザに不要なAPIを公開しない」という点にあると理解しています。その点からCommandFormにCommandのbuildメソッドを追加することはよくない方針だと思われます。

またCommandFormはCommandインスタンスを作成するために存在するクラスではありません。buildメソッドを追加することは、ユーザに誤解を生じさせる可能性が高いと考えられるので、お勧めはできません。

**Comment by satoshikumano** [comment]
CommandFormをJSONにシリアライズできるようにすれば良いのでは？

**Comment by satoshikumano** [comment]
> `ThingIFAPI.getNewCommand(CommandForm)`

ThingIFAPI.postNewCommand(CommandForm) ですかね。

**Comment by naoki-akimoto** [comment]
postNewCommandの間違いですね。

**Comment by naoki-akimoto** [comment]
CommandFormを直接JSONに変換する場合は、項目的に少なすぎるので新たなセッターメソッドを追加する必要があり、postNewCommandからアクセスする必要があるのでpublicになります。

#120 で熊野さんが言っているBuilderクラスを一つ作って、ThingIFAPIとCommandFormからCommandを生成するメソッド(これはpublicにするか、しないならリフレクションでアクセスする)を追加するっていうのが自分の意見です。

**Comment by satoshikumano** [comment]
> 項目的に少なすぎるので新たなセッターメソッドを追加する必要

JSONシリアライザーに必要なのはGetterだけではないですか？
セッターメソッドが必要な理由がわかりませんでした。

> postNewCommandからアクセスする必要があるのでpublicになります。

postNewCommandはJSONのシリアライザーにアクセスする必要がありますね。
既存の処理と同様にGsonRepositoryにシリアライザーを登録する形でできると思います。

**Comment by naoki-akimoto** [comment]
CommandとCommandFormを比較するとCommandのプロパティが倍以上多いです。それらのプロパティをCommandFormに設定すると、同時にセッターも増やす必要があるはずです。その場合はパッケージ位置の関係上publicにするしかないので本末転倒になります。

**Comment by satoshikumano** [comment]
CommandFormの生成はBuilderで行います。

CommandFormはBuilderで生成できる前提として、CommandFormにはgetterがあればJSONSerializerを実装できるので、
CommandFormからCommandを生成しなくてもリクエストが送れるのではないか？
というのが質問の趣旨でした。

**Comment by naoki-akimoto** [comment]
最低限CommandFormにissuerプロパティ(オーナーのTypedID)が必要となります。
CommandFormがissuerプロパティを持つならばJSONSerializerを使うことは可能です。

でも上記のとおりissuerプロパティのセッターが必要になるのでパッケージ位置的にpublicにするか、
Builderのビルドメソッドがpublicになる(この場合BuilderはCommandFormと同じパッケージ位置)必要があります。

**Comment by satoshikumano** [comment]
こちらと同様の方法で対処できませんか？
https://github.com/KiiPlatform/thing-if-AndroidSDK/pull/112

**Comment by naoki-akimoto** [comment]
ThingIFAPI.deserializeみたいにserializeメソッドもあれば即答できるんですが、無いので実装したりして調べてみないと何とも言えません。
多分Gsonは使用できないんではないかと予想はできますが。

**Comment by satoshikumano** [comment]
調査してみてもらえますか。

**Comment by naoki-akimoto** [comment]
了解です。

**Comment by naoki-akimoto** [comment]
#112 と同じようにserializeでの実装は可能でした。

この方法で修正するように別Issueを立ててもいいでしょうか？
その場合、送信用のCommandを作る方法が2系統(上記とGson経由)になるのでそれが若干問題になりえますが、CommandとCommandFormでは別々に作っていると考えれば問題ないとも言えます。

**Comment by satoshikumano** [comment]
ありがとうございます。

> 別Issueを立ててもいいでしょうか
お願いします。

**Comment by naoki-akimoto** [comment]
StatePredicateの2つのメソッドはどちらも削除して問題ありません。
テストでは未使用で、運用上もAPIの入力にはならず、また値を変更する場合は新しいStatePredicateを作成すればいいだけなので。

Triggerの4つのメソッドのも削除して問題ありません。
運用上Triggerを入力にするAPIが存在しないので設定させる意味がありません。
ただし、テストではパッケージ位置の問題が出るのでMockitoなどを導入して内部フィールドに値を設定するなど、一部対応が必要となります。

TriggeredServerCodeResultのメソッドも削除して問題ありません。
テストでは未使用で、APIでも入力には来ないクラスなので。

**Comment by naoki-akimoto** [comment]
Commandのセッターメソッドの修正は、テストをTriggerと同じように修正しなければならないので #127 マージ後こちらで行います。

**Comment by naoki-akimoto** [comment]
修正が完了しているので閉じます。
