### ISSUE TITLE
Release v0.13.0

### ISSUE THREAD

**Issue by shinsuke-nara** [KiiPlatform/thing-if-AndroidSDK#145]
### New feature
- Onboard with options (#104)
- Cross thing command trigger with optional data (#119)
- Server code triggers with optional data (#136)
### Improvement
- retry on connection failure by PUT (#102)
- Remove unnecessary public setter methods (#128)
- Add javadoc for some method in `Trigger` class (#130)
### Bug fix
- Fix javadoc (#121)
- `Trigger#getTargetID()` returns ID of `ThingIFAPI#getTarget()` (#112)
### Internal
- make request body from CommandForm. (#127)

Related PR: #144

**Comment by satoshikumano** [comment]
released
