### ISSUE TITLE
Current AliasAction can not represent an array of actions

### ISSUE THREAD

**Issue by shinsuke-nara** [KiiPlatform/thing-if-AndroidSDK#281]
Current `AliasAction` can not represent an array of actions. It does not match specification.

Related PR: KiiPlatform/thing-if-iOSSDK#376

**Comment by yongpingchen** [comment]
#287 
TODO:
- [ ]  improve ActionAdapter/AliasActionAdapter
- [ ]  fix failure small/large tests caused by the changes
- [ ] refactor ThingIFAPI#actionTyeps, make key as object combining with alias and actionName
