### ISSUE TITLE
No one set Command.firedByTriggerID

### ISSUE THREAD

**Issue by naoki-akimoto** [KiiPlatform/thing-if-AndroidSDK#77]
テスト側以外にCommandのfiredByTriggerIDフィールドを設定するコードが有りませんでした。
報告のためIssueを上げます。

**Comment by shinsuke-nara** [comment]
@naoki-akimoto 修正をお願いします。
サーバからコマンド取得時のHTTPレスポンスにfiredByTriggerIDが含まれるので、それを取り出してCommandに設定するようにしてください。

**Comment by naoki-akimoto** [comment]
明示的に設定するものが無いだけで、GSONライブラリによりJSON文字列から直接Commandクラスをデシリアライズしていました。
よって修正の必要はありません。

実際にThingIFAPI_ListCommandTest#listCommandsWithBestEffortLimitZeroTest内でモックのレスポンスに設定されたJSONのfiredByTriggerIDがレスポンス処理後に作成されたCommandに反映されるのを確認しました。

**Comment by shinsuke-nara** [comment]
観測ミスでした。closeします。
